// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwFLLKwl9vHDDNw4i6023fTxrCwqWxhs',
    appId: '1:34123444:android:f747a6608636f8a13531e1',
    messagingSenderId: '34123444',
    projectId: 'taxy-2026',
    databaseURL: 'https://taxy-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxy-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAID3olrgP4lZy1B5ObLY8MLzenPUsP1q8',
    appId: '1:34123444:ios:2ad54c12955252403531e1',
    messagingSenderId: '34123444',
    projectId: 'taxy-2026',
    databaseURL: 'https://taxy-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxy-2026.firebasestorage.app',
    iosClientId: '34123444-4opafnacn90rq03btheb5qjk1mn5giiv.apps.googleusercontent.com',
    iosBundleId: 'com.goride.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0TnoNXrathRCIczdYVSYLV9FW1ocZU4o',
    appId: '1:34123444:web:f88f977c9615d2b53531e1',
    messagingSenderId: '34123444',
    projectId: 'taxy-2026',
    authDomain: 'taxy-2026.firebaseapp.com',
    databaseURL: 'https://taxy-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxy-2026.firebasestorage.app',
    measurementId: 'G-NVL4SPYH9T',
  );

}